### ISSUE TITLE
openssl error maybe ? 

### ISSUE THREAD

**Issue by matrixhax** [justNoOneHere/MnemonicBalanceChecker#1]
hello i got this error while trying your script :

Error generating mnemonic: Error: error:0308010C:digital envelope routines::unsupported
Error generating mnemonic: Error: error:0308010C:digital envelope routines::unsupported

i installed the rquired libraries

**Comment by justNoOneHere** [comment]
Hi, what version of nodejs you have? Did you install the libraries with  --no-audit?

**Comment by justNoOneHere** [comment]
Ah ok i will fix it soon.

**Comment by justNoOneHere** [comment]
https://github.com/justNoOneHere/MnemonicBalanceChecker/commit/47981aa2ad54efcc31bb13aceccf7e88cb7c45d0

thank u :D
