### ISSUE TITLE
Does not execute. Missing modules.

### ISSUE THREAD

**Issue by J9B10** [justNoOneHere/MnemonicBalanceChecker#2]
Does not execute. Missing modules.

It is not possible to run the application because the module files are missing inside the folder.

Missing files:

package.json

package-lock.json

It is possible to use "npm install" to download the modules, but it needs "package.json" and "package-lock.json".

Please include the necessary files.
![2023-05-16 11 55 21](https://github.com/justNoOneHere/MnemonicBalanceChecker/assets/98818736/9fddcfd6-37c3-4ead-b6d2-c5bce8c8d5b6)

**Comment by justNoOneHere** [comment]
Use 
```npm install fs axios bip39 hdkey ethers ethereumjs-util prompt-sync```
