### ISSUE TITLE
Not a Function

### ISSUE THREAD

**Issue by arashisec** [justNoOneHere/MnemonicBalanceChecker#5]
I get this error result :

How Many bits of entropy : 128
How Many Mnemonic To Generate : 5
Error generating mnemonic: TypeError: ethers.Wallet.fromMnemonic is not a function                                                                      Error generating mnemonic: TypeError: ethers.Wallet.fromMnemonic is not a function                                                                      Error generating mnemonic: TypeError: ethers.Wallet.fromMnemonic is not a function                                                                      Error generating mnemonic: TypeError: ethers.Wallet.fromMnemonic is not a function                                                                      Error generating mnemonic: TypeError: ethers.Wallet.fromMnemonic is not a function

**Comment by justNoOneHere** [comment]
install the full libraries ...
npm install fs axios bip39 hdkey ethereumjs-util prompt-sync
